esphome:
  name: ESPHome Netgear M5

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
 - source: github://andrewbackway/esphome-netgear-m5

logger:

web_server:
  version: 3
  local: true

netgear-m5:
  id: netgear_m5_hub
  host: HOSTIP
  password: PASSWORD
  poll_interval: 10s

sensor:
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Battery Level
    path: power.battChargeLevel
    unit_of_measurement: "%"
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Device Temperature
    path: general.devTemperature
    unit_of_measurement: "°C"
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: RSSI
    path: wwan.signalStrength.rssi
    unit_of_measurement: "dBm"
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: RSRP
    path: wwan.signalStrength.rsrp
    unit_of_measurement: "dBm"
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: RSRQ
    path: wwan.signalStrength.rsrq
    unit_of_measurement: "dB"
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: WiFi Clients
    path: wifi.clientCount
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Cell Tower ID
    path: wwanadv.cellId
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Bars
    path: wwan.signalStrength.bars
    
text_sensor:
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Device Name
    path: general.deviceName
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Mobile Carrier
    path: wwan.registerNetworkDisplay 
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Mobile Band
    path: wwan.connectionText    
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Mobile Status
    path: wwan.connection
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Offload WiFi SSID
    path: wifi.offload.connectionSsid
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Offload Scan Progress
    path: wifi.offload.scanProgress

binary_sensor:
  - platform: netgear-m5
    netgear_m5_id: netgear_m5_hub
    name: Offloading via WiFi
    path: wifi.offload.status
    on_value: "On"
    off_value: "Off"